### PR TITLE
Builds with Go 1.16.6

### PR DESCRIPTION
**Pull request by codefromthecrypt**
https://github.com/golang/go/issues?q=milestone%3AGo1.16.6+label%3ACherryPickApproved

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
hmm we have something to consider which is that the e2e looks for a coherent version. Actually the linux+windows vs darwin versions are on different schedules until https://github.com/envoyproxy/envoy/issues/16830 (which seems inactive).

We may want to consider using a regex vs a strict version match here in order to avoid locking up things.. WDTY @mathetake

**Comment by codefromthecrypt** [comment]
also it is tricky but "latestVersion" in https://archive.tetratelabs.io/envoy/envoy-versions.json causes this.. we may want to consider not publishing at all until os/x is done as basically it ends up latest, except darwin which introduces some skew edge cases in tests and usage

**Comment by codefromthecrypt** [comment]
opened https://github.com/tetratelabs/archive-envoy/issues/15 on this topic

**Comment by codefromthecrypt** [comment]
tetratelabs/archive-envoy#16 works around the build outage by pinning 1.18.3

**Review by mathetake — APPROVED** [review]

**Pull request merged**
