### PR TITLE
build: updates to latests tools and envoy version

### PR DESCRIPTION
**Pull request by codefromthecrypt**

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
looks like we need to lift the windows stuff from wazero back here, huh :D

**Comment by evacchi** [comment]
you mean the env vars/ifs right? 🤔

**Comment by codefromthecrypt** [comment]
> you mean the env vars/ifs right? 🤔

yeah all that. basically, the most recent working version of the packaging flow needs to be backported here. if you are game for pushing commits millions of good karma will rain from above :D

**Comment by evacchi** [comment]
🎶 *I miss the karma rains in packaging* 🎶

**Review by evacchi — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
ps this PR isn't high priority so I will let it sit while we finish up wazero

**Comment by codefromthecrypt** [comment]
disregard last comment, as @evacchi decided to karmafy

**Comment by codefromthecrypt** [comment]
hmm still packaging glitch decrypting the password.

**Comment by evacchi** [comment]
> that fails for me too on my machine 🤔
> 
> EDIT: I think `func-e.p12` got corrupted or replaced, by running the lines here https://github.com/tetratelabs/func-e/blob/master/Makefile#L279-L280 fixes it for me
> 
> ```shell
> keytool -genkey -alias func-e -storetype PKCS12 -keyalg RSA -keysize 2048 -storepass func-e-bunch \
>    -keystore func-e.p12 -dname "O=func-e,CN=func-e.io" -validity 3650
> ```

I remember I had this issue at some point! I addressed this in #444 by committing the result of this command

**Pull request closed without merging**
